#!/usr/bin/python
import os
import sys
import argparse

from twisted.python import log
from twisted.internet import reactor, task

from hc import server, config
from hc.hacks import HackedSerialPort
from hc.util import trace
from hc.machine_proto import MachineTalk


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='hacked-cnc file feeder')
    parser.add_argument('FILE', help='File to feed')

    args = parser.parse_args()

    if not os.access(args.FILE, os.R_OK):
        sys.exit(0)

    tcpfactory = server.MonitorFactory()
    reactor.listenTCP(config.get('monitor_port'), tcpfactory)

    proto = MachineTalk(tcpfactory)
    tcpfactory.sr = proto

    def bfs(proto):
        proto.buffer_stat()

    def start_bfs(proto):
        b = task.LoopingCall(bfs, proto)
        b.start(1)

    proto.ready_cb.addCallback(proto.feed_file, args.FILE)
    proto.ready_cb.addCallback(start_bfs)
    proto.ready_cb.addErrback(log.err)

    proto.exit_when_done = True


    HackedSerialPort(proto, config.get('port'), reactor,
                     baudrate=config.get('baudrate'))
    reactor.run()
