#!/usr/bin/python
import argparse

from twisted.python import log
from twisted.internet import stdio, reactor

from hc import server, config
from hc.hacks import HackedSerialPort
from hc.util import trace
from hc.machine_proto import MachineTalk

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='hacked-cnc server')
    parser.add_argument('--stdio', action="store_true", default=False,
                        help='Use stdio')

    args = parser.parse_args()

    @trace
    def handle_temp(cmd):
        print 'TEMP'
        print cmd

    @trace
    def probe(proto):
        c = proto.cmd('M114')
        c.d.addCallback(handle_temp)

    def bfs(proto):
        proto.buffer_stat()

    tcpfactory = server.MonitorFactory()
    reactor.listenTCP(config.get('monitor_port'), tcpfactory)

    proto = MachineTalk(tcpfactory)
    tcpfactory.sr = proto

    proto.ready_cb.addCallback(probe)
    proto.ready_cb.addErrback(log.err)
    if args.stdio:
        stdio.StandardIO(proto)
    else:
        HackedSerialPort(proto, config.get('port'), reactor,
                         baudrate=config.get('baudrate'))

    reactor.run()
