#!/usr/bin/python
import argparse

from twisted.python import log
from twisted.internet import stdio, reactor

import hc
from hc import server, config, monitor
from hc.hacks import HackedSerialPort
from hc.machine_proto import MachineTalk

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='hacked-cnc server')
    parser.add_argument('--stdio', action="store_true", default=False,
                        help='Use stdio')

    args = parser.parse_args()

    hc.setup()

    server = server.build()
    monitor = monitor.build_server()

    proto = MachineTalk(server)
    server.sr = proto
    monitor.sr = proto
    proto.monitor = monitor

    proto.ready_cb.addErrback(log.err)
    if args.stdio:
        stdio.StandardIO(proto)
    else:
        HackedSerialPort(proto, config.get('port'), reactor,
                         baudrate=config.get('baudrate'))

    reactor.run()
