#!/usr/bin/python2
import argparse

from twisted.internet import reactor

import hc


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='hacked-cnc command sender')
    parser.add_argument('CMD', help='Command to send')

    args = parser.parse_args()
    cmd = args.CMD

    hc.setup()

    def sendcmd(proto):
        proto.sendLine(cmd)
        proto.quit()
        reactor.callLater(1, reactor.stop)

    hc.client.build(sendcmd)
    reactor.run()
