#!/usr/bin/python
# -*- encoding: utf-8 -*-

import hctests

from hc import util


class UtilTestCase(hctests.TestCase):
    def test_data_encoding(self):
        """
        Test data ecoding and decoding funtions
        """

        d = [{'lala': 13.37}]
        enc = util.encdata(d)
        dec = util.decdata(enc)

        self.assertEqual(d, dec)

    def test_msg_encoding(self):
        msg = 'G0 X1.0 Y1337 F123'

        enc = util.enc_msg(msg)
        dec = util.dec_msg(enc)

        self.assertEqual(None, dec[0])
        self.assertEqual(msg, dec[1])

    def test_indexed_msg_encoding(self):
        msg = 'G0 X1.0 Y1337 F123'
        idx = 123

        enc = util.enc_msg(msg, idx)
        dec = util.dec_msg(enc)
        print enc
        print dec

        self.assertEqual(idx, dec[0])
        self.assertEqual(msg, dec[1])

if __name__ == "__main__":
    hctests.main()
